### ISSUE TITLE
Doctor reservation: Kanban Board

### ISSUE THREAD

**Issue by carlosmuerto** [carlosmuerto/doctor_reservation_api#11]
# Doctor reservation: Kanban Board

### [Works assignment distribution chart](https://github.com/users/carlosmuerto/projects/9/insights/2)

# Repositories
## Members
- @Aduda-Boaz 
- @LokurasRlz 
- @ErikStoupignan 
- @carlosmuerto 

### Kanban Board
![imagen](https://user-images.githubusercontent.com/34493013/210821801-79dcbad4-4dea-40d4-b43e-b8bdec01a5f1.png)
### Works assignment distribution chart
![imagen](https://user-images.githubusercontent.com/34493013/210831683-09e72a89-e789-4d0a-9f5e-4cae7adddc7c.png)

**Comment by Meltrust** [comment]
Hi @carlosmuerto,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have been assigned✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] Some tasks do not have a description:

![image](https://user-images.githubusercontent.com/57421823/210827946-a42df14a-f475-4abb-968e-c3dccc4fcd88.png)

Kindly ensure all your tasks have descriptions.

- [ ] This is the points distribution at the time at this review:

LokurasRlz 15
Aduda-Boaz 15
carlosmuerto 14
ErikStoupignan  8

As you can see, @ErikStoupignan has a lot fewer points than the other members of the team.  Please ensure that no team member has more or less than 4 points difference compared to the other members.  TIP:  Just ensure @ErikStoupignan has at least 3 more points, and/or reassign some tasks.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ErikStoupignan** [comment]
## Hello @Meltrust, good morning. 

We are going to correct the detail of the descriptions on the cards. Thanks for the observation. ✅ 

And I would like to tell you that in the assignment of activities, all the members of the team are similar in scores.

Our Kanban board has a "done" column on the right that you may not have seen. In any case, in the activity assignment graph, you can confirm that all the members have a similar percentage of work.

### Kanban board  job assignments 
![image](https://user-images.githubusercontent.com/106561762/210832546-0b06551d-b729-4ae1-8573-d3a91d589cf6.png)

### Kanban board - all columns
![image](https://user-images.githubusercontent.com/106561762/210832794-5c8d1b88-630d-41d9-aa65-9dd48957debf.png)

**Comment by vichuge** [comment]
Hi dear student, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
